# Generated by Django 6.0.7 on 2026-08-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(
                        help_text="The full legal name of the student being onboarded.",
                        max_length=100,
                    ),
                ),
                (
                    "student_age",
                    models.IntegerField(
                        help_text="The age of the student (must be between 5 and 18 inclusive)."
                    ),
                ),
                (
                    "student_email_address",
                    models.EmailField(
                        help_text="The contact email address for student-related notifications.",
                        max_length=254,
                    ),
                ),
                (
                    "student_phone_number",
                    models.CharField(
                        help_text="The 10-digit numeric mobile or home telephone contact number.",
                        max_length=10,
                    ),
                ),
                (
                    "guardian_consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Flag indicating if the parent or legal guardian has formally given consent.",
                    ),
                ),
                (
                    "educational_institution_name",
                    models.CharField(
                        help_text="The name of the educational institution/school the student is enrolled in.",
                        max_length=150,
                    ),
                ),
                (
                    "parent_guardian_full_name",
                    models.CharField(
                        help_text="The full legal name of the primary parent or legal guardian.",
                        max_length=100,
                    ),
                ),
                (
                    "learning_difficulty_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of any learning difficulties or special accommodations needed.",
                        null=True,
                    ),
                ),
                (
                    "local_support_authority_region",
                    models.CharField(
                        help_text="The Local Support Authority (LSA) region overseeing educational support.",
                        max_length=100,
                    ),
                ),
                (
                    "record_created_at_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this onboarding record was created.",
                    ),
                ),
            ],
        ),
    ]
